init:
  - git config --global core.autocrlf false
environment:
  matrix:
    - nodejs_version: "5"
version: "{build}"
build: off
deploy: off
install:
  - ps: Install-Product node $env:nodejs_version
  - npm install
test_script:
  - node --version
  - npm --version
  - npm test
